// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectCountry } from "./SelectCountry";

export interface CityExtendedSchema { id: bigint, name: string, country: SelectCountry, }