// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountrySummarizedSchema } from "./CountrySummarizedSchema";

export interface CityExtendedSchema { id: number, name: string, country: CountrySummarizedSchema, }