// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectCity } from "./SelectCity";

export interface CountryExtendedSchema { id: bigint, name: string, continent: string | null, cities: Array<SelectCity>, is_archived: boolean, }