// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CitySummarizedSchema } from "./CitySummarizedSchema";

export interface CountryExtendedSchema { id: number, name: string, continent: string | null, cities: Array<CitySummarizedSchema>, isArchived: boolean, }