// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UpdateCountry { name?: string | null, continent?: string | null, is_archived?: boolean | null, }